import 'package:flutter/material.dart';
import '../widgets/event_card.dart'; 
import '../../core/theme.dart'; 
// تأكدي من استيراد ملف الثيم لكي يتعرف الكود على AppColors و AppTextStyles
// import 'package:your_project_name/theme/theme.dart'; 

class SmartTourScreen extends StatelessWidget {
  const SmartTourScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final List<Map<String, dynamic>> tourSteps = [
      {
        "time_slot": "10:00 AM",
        "title": "National Museum",
        "image": "https://pnu.edu.sa/en/Announcements/PublishingImages/museum.jpg",
        "desc": "Start your day with a cultural trip through history.",
        "status": "Low",
      },
      {
        "time_slot": "01:30 PM",
        "title": "Traditional Lunch in Diriyah",
        "image": "https://www.visitsaudi.com/content/dam/saudi-tourism/media/diriyah/at-turaif.jpg",
        "desc": "Enjoy authentic Saudi cuisine in the heart of Diriyah.",
        "status": "Moderate",
      },
      {
        "time_slot": "04:00 PM",
        "title": "Library & Workshop",
        "image": "https://example.com/library.jpg",
        "desc": "Attend an AI workshop and explore modern libraries.",
        "status": "Low",
      },
    ];

    return Scaffold(
      // استخدام لون الخلفية من كلاس AppColors الخاص بكِ
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: const Text(
          "Your Smart Tour Plan", 
          style: AppTextStyles.sectionTitle
        ),
        backgroundColor: Colors.transparent, 
        elevation: 0,
        centerTitle: true,
        // تأكدي من استخدام لون الأيقونات من الثيم
        iconTheme: const IconThemeData(color: AppColors.primary),
      ),
      body: Column(
        children: [
          // الجزء العلوي التوضيحي باستخدام كلاسات الثيم
          Container(
            margin: const EdgeInsets.all(16),
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AppColors.white,
              borderRadius: BorderRadius.circular(15),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.05),
                  blurRadius: 10,
                  offset: const Offset(0, 4),
                ),
              ],
            ),
            child: Row(
              children: [
                const Icon(Icons.auto_awesome, color: Colors.amber, size: 20),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    "This tour was generated by AI based on your interest in Heritage and AI.",
                    style: AppTextStyles.subtitle.copyWith(
                      color: AppColors.textMain,
                      fontStyle: FontStyle.italic,
                    ),
                  ),
                ),
              ],
            ),
          ),
          
          Expanded(
            child: ListView.builder(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              itemCount: tourSteps.length,
              itemBuilder: (context, index) {
                final step = tourSteps[index];
                return IntrinsicHeight(
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // عمود التايم لاين
                      SizedBox(
                        width: 75,
                        child: Column(
                          children: [
                            const SizedBox(height: 10),
                            Text(
                              step['time_slot'], 
                              style: AppTextStyles.subtitle.copyWith(
                                fontWeight: FontWeight.bold,
                                color: AppColors.primary,
                                fontSize: 12,
                              ),
                              textAlign: TextAlign.center,
                            ),
                            const SizedBox(height: 8),
                            Expanded(
                              child: Container(
                                width: 2,
                                color: AppColors.divider.withOpacity(0.5),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 12),
                      // بطاقة الفعالية
                      Expanded(
                        child: Padding(
                          padding: const EdgeInsets.only(bottom: 20),
                          child: EventCard(
                            title: step['title'],
                            imagePath: step['image'],
                            description: step['desc'],
                            schedule: step['time_slot'],
                            price: "Part of Tour",
                            crowdStatus: step['status'],
                            onSuggestRoute: () {},
                          ),
                        ),
                      ),
                    ],
                  ),
                );
              },
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {},
        label: const Text("Regenerate Plan", style: AppTextStyles.buttonText),
        icon: const Icon(Icons.refresh),
        backgroundColor: AppColors.primary,
        foregroundColor: AppColors.white,
      ),
    );
  }
}