import 'package:flutter/material.dart';
import '../widgets/event_card.dart'; // تأكدي من المسار

class SmartTourScreen extends StatelessWidget {
  const SmartTourScreen({super.key});

  @override
  Widget build(BuildContext context) {
    // قائمة الفعاليات المقترحة للجولة (مرتبة حسب الوقت)
    final List<Map<String, dynamic>> tourSteps = [
      {
        "time_slot": "10:00 AM",
        "title": "National Museum",
        "image": "https://pnu.edu.sa/en/Announcements/PublishingImages/museum.jpg",
        "desc": "Start your day with a cultural trip through history.",
        "status": "Low",
      },
      {
        "time_slot": "01:30 PM",
        "title": "Traditional Lunch in Diriyah",
        "image": "https://www.visitsaudi.com/content/dam/saudi-tourism/media/diriyah/at-turaif.jpg",
        "desc": "Enjoy authentic Saudi cuisine in the heart of Diriyah.",
        "status": "Moderate",
      },
      {
        "time_slot": "04:00 PM",
        "title": "Library & Workshop",
        "image": "https://example.com/library.jpg",
        "desc": "Attend an AI workshop and explore modern libraries.",
        "status": "Low",
      },
    ];

    return Scaffold(
      backgroundColor: const Color(0xFFF0F2F5),
      appBar: AppBar(
        title: const Text("Your Smart Tour Plan", style: TextStyle(fontWeight: FontWeight.bold)),
        backgroundColor: const Color(0xFF1A237E),
        centerTitle: true,
      ),
      body: Column(
        children: [
          // جزء علوي توضيحي
          Container(
            padding: const EdgeInsets.all(16),
            color: Colors.white,
            child: Row(
              children: [
                const Icon(Icons.auto_awesome, color: Colors.amber),
                const SizedBox(width: 10),
                const Expanded(
                  child: Text(
                    "This tour was generated by AI based on your interest in Heritage and AI.",
                    style: TextStyle(fontStyle: FontStyle.italic),
                  ),
                ),
              ],
            ),
          ),
          
          // قائمة المسار (Timeline)
          Expanded(
            child: ListView.builder(
              padding: const EdgeInsets.all(16),
              itemCount: tourSteps.length,
              itemBuilder: (context, index) {
                final step = tourSteps[index];
                return Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // عمود الوقت والخط الزمني
                    Column(
                      children: [
                        Text(step['time_slot'], style: const TextStyle(fontWeight: FontWeight.bold)),
                        Container(
                          width: 2,
                          height: 250, // طول الخط بين الفعاليات
                          color: const Color(0xFF1A237E).withOpacity(0.3),
                        ),
                      ],
                    ),
                    const SizedBox(width: 15),
                    // استخدام الكارد
                    Expanded(
                      child: EventCard(
                        title: step['title'],
                        imagePath: step['image'],
                        description: step['desc'],
                        schedule: step['time_slot'],
                        price: "Part of Tour",
                        crowdStatus: step['status'],
                        onSuggestRoute: () {
                          // كود يفتح الخريطة لهذا المسار تحديداً
                        },
                      ),
                    ),
                  ],
                );
              },
            ),
          ),
        ],
      ),
      // زر لتأكيد الرحلة أو إعادة توليدها
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {},
        label: const Text("Regenerate Plan"),
        icon: const Icon(Icons.refresh),
        backgroundColor: const Color(0xFF1A237E),
      ),
    );
  }
}