// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNyWguyHXR-fomByifyb9XXk46IB19EdI',
    appId: '1:417277582360:web:6991a6252a89589b01776d',
    messagingSenderId: '417277582360',
    projectId: 'wsal-2b30a',
    authDomain: 'wsal-2b30a.firebaseapp.com',
    databaseURL: 'https://wsal-2b30a-default-rtdb.firebaseio.com',
    storageBucket: 'wsal-2b30a.firebasestorage.app',
    measurementId: 'G-NNCFS3756T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnpvcMaEyKMB4OhT3aidY8WYxAyi4Nhhg',
    appId: '1:417277582360:android:8b26934d5fb4b8df01776d',
    messagingSenderId: '417277582360',
    projectId: 'wsal-2b30a',
    databaseURL: 'https://wsal-2b30a-default-rtdb.firebaseio.com',
    storageBucket: 'wsal-2b30a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNyWguyHXR-fomByifyb9XXk46IB19EdI',
    appId: '1:417277582360:web:6f1a47f8c75720d801776d',
    messagingSenderId: '417277582360',
    projectId: 'wsal-2b30a',
    authDomain: 'wsal-2b30a.firebaseapp.com',
    databaseURL: 'https://wsal-2b30a-default-rtdb.firebaseio.com',
    storageBucket: 'wsal-2b30a.firebasestorage.app',
    measurementId: 'G-TMM95KS1LY',
  );
}
